config/routes.rb
Rails.application.routes.draw do
  resources :projects

  get 'dashboards/index'
  root to: 'projects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true, length: { maximum: 160 }
    validates :start_date, presence: true
    validates :due_date, presence: true
    

    enum status: [:Propuesta, :Progreso, :Terminado]
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
    http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only: [:index]
    def index
        @q = Project.ransack(params[:q])
        @projects = @q.result(distinct: true)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  

  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @q = Project.ransack(params[:q])
    @projects = @q.result(distinct: true)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :start_date, :due_date, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/dashboards/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start date</th>
      <th>Due date</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.start_date %></td>
        <td><%= project.due_date %></td>
        <td><%= project.status %></td>
        <td><%= link_to 'Mostrar', project %></td>
        <td><%= link_to 'Editar', edit_project_path(project) %></td>
        <td><%= link_to 'Eliminar', project, method: :delete, data: { confirm: '¿Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Proyecto', new_project_path %> <br>
<%= link_to  "Dashboard de Proyectos", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GestorDeProyectos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> No se puede guardar este proyecto:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nombre_del_proyecto %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :Descripcion %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :Fecha_de_comienzo %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :Fecha_de_termino %>
    <%= form.date_select :due_date %>
  </div>

  <div class="field">
    <%= form.label :Estado %>
    <%= form.select :status, Project.statuses.keys %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="row">
    <div class="col-md-8 offset-md-2">
        <div class="jumbotron">
            <h1 class="display-4">Dashboard de Proyectos</h1>
            <hr class="my-4">
            <p>Plataforma para creacion de proyectos</p>
            <%= link_to 'Entrar a Plataforma para crear Proyectos', dashboards_index_path %>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-3 offset-md-2">
        <%= search_form_for @q do |f| %>
            <div class="form-group">
                <%= f.label :status_eq, "Estado" %>
                <%= f.select :status_eq, options_for_select(Project.statuses ,
@q.status_eq), {},{class: "form-control"} %>
            </div>

            <%= f.submit "Buscar", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>




<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr>
                <th>Nombre</th>
                <th>Descripcion</th>
                <th>Fecha de Inicio</th>
                <th>Fecha de Termino</th>
                <th>Estado actual del Proyecto</th>
                <th colspan="3"></th>
                </tr>
            </thead>


            <tbody>
                <% @projects.each do |project| %>
                    <tr>
                        <td><%= project.name %></td>
                        <td><%= project.description %></td>
                        <td><%= project.start_date %></td>
                        <td><%= project.due_date %></td>
                        <td><%= project.status %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>

    </div>
</div>

app/views/projects/new.html.erb
<h1>Formulario para creacion de Proyectos</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @project.start_date %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @project.due_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @project.status %>
</p>

<%= link_to 'Editar', edit_project_path(@project) %> |
<%= link_to 'Index', projects_path %>